name: Build and Publish Container Image

on:
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.image-tag.outputs.tag }}
      image-name: ${{ steps.repo.outputs.IMAGE_NAME }}
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase repository name
        id: repo
        run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.repo.outputs.IMAGE_NAME }}
          tags: |
             type=ref,event=branch
             type=ref,event=pr
             type=semver,pattern={{version}}
             type=semver,pattern={{major}}.{{minor}}
             type=semver,pattern={{major}}
             type=raw,value=latest,enable={{is_default_branch}}
             type=sha

      - name: Build and push container image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set test image tag
        id: image-tag
        run: |
          # Use the first tag from metadata for testing
          TAGS="${{ steps.meta.outputs.tags }}"
          FIRST_TAG=$(echo "$TAGS" | head -n1)
          echo "tag=$FIRST_TAG" >> $GITHUB_OUTPUT
          echo "Using image tag for testing: $FIRST_TAG"

  test-image:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase repository name
        id: repo
        run: echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create test directories
        run: |
          mkdir -p /tmp/test-photos/landing
          mkdir -p /tmp/test-photos/converted
          # Create dummy CR3 files for testing
          touch /tmp/test-photos/landing/test1.cr3
          touch /tmp/test-photos/landing/test2.cr3

      - name: Test container image (dry-run)
        run: |
          # Use the image tag from the build job
          IMAGE="${{ needs.build-and-push.outputs.image-tag }}"
          echo "Testing image: $IMAGE"
          docker run --rm \
            -v "/tmp/test-photos/landing:/photos/landing:ro" \
            -v "/tmp/test-photos/converted:/photos/converted" \
            "$IMAGE" \
            --dry-run

      - name: Verify dnglab installation
        run: |
          IMAGE="${{ needs.build-and-push.outputs.image-tag }}"
          echo "Verifying dnglab in image: $IMAGE"
          docker run --rm "$IMAGE" sh -c "dnglab --version"